# Generated by Django 3.0.5 on 2020-08-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan1', '0040_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='acc',
            fields=[
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plan1.city')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('cost_per_night', models.IntegerField()),
            ],
        ),
    ]
