# Generated by Django 3.0.5 on 2020-08-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='acc',
        ),
    ]
