# Generated by Django 3.0.5 on 2020-08-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('final', '0002_delete_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('cost_per_night', models.IntegerField()),
            ],
        ),
    ]
