# Generated by Django 3.0.5 on 2020-10-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0041_auto_20201010_1542'),
        ('final', '0003_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan1.city'),
        ),
    ]
