# Generated by Django 3.0.5 on 2020-11-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_flights_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
