# Generated by Django 3.0.5 on 2020-06-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
