# Generated by Django 3.0.5 on 2020-06-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0002_auto_20200613_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='phno',
            field=models.CharField(max_length=10),
        ),
    ]
