# Generated by Django 3.0.5 on 2020-06-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0004_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='names',
        ),
    ]
