# Generated by Django 3.0.5 on 2020-06-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0005_auto_20200617_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='names',
        ),
    ]
