# Generated by Django 3.0.5 on 2020-06-20 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addUser', '0007_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='s1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=3)),
                ('people', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addUser.User')),
            ],
        ),
    ]
