# Generated by Django 3.0.5 on 2020-06-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0007_user_name'),
        ('plan1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s1',
            name='id',
        ),
        migrations.AlterField(
            model_name='s1',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='addUser.User'),
        ),
    ]
