# Generated by Django 3.0.5 on 2020-07-20 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0007_user_name'),
        ('plan1', '0002_auto_20200620_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s1',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='addUser.User'),
        ),
    ]
