# Generated by Django 3.0.5 on 2020-07-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0004_auto_20200720_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('counrty', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
            ],
        ),
    ]
