# Generated by Django 3.0.5 on 2020-07-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0005_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='weather',
            field=models.CharField(default='hot', max_length=3),
            preserve_default=False,
        ),
    ]
