# Generated by Django 3.0.5 on 2020-07-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0006_city_weather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
