# Generated by Django 3.0.5 on 2020-07-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0012_s2'),
    ]

    operations = [
        migrations.CreateModel(
            name='attractions',
            fields=[
                ('attract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('country', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='country',
        ),
    ]
