# Generated by Django 3.0.5 on 2020-07-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0013_auto_20200722_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='country',
            field=models.CharField(default='q', max_length=100),
            preserve_default=False,
        ),
    ]
