# Generated by Django 3.0.5 on 2020-07-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0014_attractions_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attractions',
        ),
    ]
