# Generated by Django 3.0.5 on 2020-07-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0015_delete_attractions'),
    ]

    operations = [
        migrations.CreateModel(
            name='attractions',
            fields=[
                ('attract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('type', models.CharField(max_length=3)),
            ],
        ),
    ]
