# Generated by Django 3.0.5 on 2020-07-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0016_attractions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s2',
            old_name='budget',
            new_name='budget_max',
        ),
        migrations.AddField(
            model_name='s2',
            name='budget_min',
            field=models.IntegerField(default='hu'),
            preserve_default=False,
        ),
    ]
