# Generated by Django 3.0.5 on 2020-07-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0017_auto_20200725_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='s2',
        ),
    ]
