# Generated by Django 3.0.5 on 2020-07-25 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0019_s2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='s2',
        ),
    ]
