# Generated by Django 3.0.5 on 2020-07-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0021_s2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s2',
            old_name='budget_max',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='s2',
            name='budget_min',
        ),
    ]
