# Generated by Django 3.0.5 on 2020-07-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0022_auto_20200725_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='s2',
        ),
    ]
