# Generated by Django 3.0.5 on 2020-07-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0024_s2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s2',
            old_name='budget',
            new_name='bud',
        ),
    ]
