# Generated by Django 3.0.5 on 2020-07-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0025_auto_20200725_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s2',
            old_name='bud',
            new_name='budget',
        ),
    ]
