# Generated by Django 3.0.5 on 2020-07-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0028_s2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='s2',
        ),
    ]
