# Generated by Django 3.0.5 on 2020-08-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0032_s2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='s2',
        ),
    ]
