# Generated by Django 3.0.5 on 2020-08-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0035_s3_s3_fam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3_fam',
            name='user',
        ),
        migrations.DeleteModel(
            name='s3',
        ),
        migrations.DeleteModel(
            name='s3_fam',
        ),
    ]
