# Generated by Django 3.0.5 on 2020-08-18 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('plan1', '0037_s3'),
    ]

    operations = [
        migrations.CreateModel(
            name='s4',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('acc', models.CharField(max_length=5)),
                ('tran', models.CharField(max_length=4)),
            ],
        ),
    ]
