# Generated by Django 3.0.5 on 2020-08-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0038_s4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
