# Generated by Django 3.0.5 on 2020-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0039_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_code', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=3)),
            ],
        ),
    ]
