# Generated by Django 3.0.5 on 2020-10-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0040_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='country',
        ),
        migrations.AddField(
            model_name='attractions',
            name='desc',
            field=models.TextField(default='N/1', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attractions',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan1.city'),
        ),
    ]
