# Generated by Django 3.0.5 on 2020-10-28 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0041_auto_20201010_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s1',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='s2',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='s3',
            name='type',
        ),
        migrations.RemoveField(
            model_name='s4',
            name='acc',
        ),
    ]
