# Generated by Django 3.0.5 on 2020-11-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0042_auto_20201028_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3',
            name='type',
            field=models.CharField(default=123456789, max_length=9),
            preserve_default=False,
        ),
    ]
