# Generated by Django 3.0.5 on 2020-11-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan1', '0043_s3_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='time',
            field=models.CharField(default='mor', max_length=3),
            preserve_default=False,
        ),
    ]
